-- ============================================================================
-- Network Intel — add authentication to an EXISTING database
-- ============================================================================
-- Run this against a live database. It is purely additive and fully idempotent:
-- it creates two tables and their indexes, drops nothing, and touches no existing
-- row. Running it twice is a no-op.
--
-- (schema-redesign.sql also contains these tables, but that script DROPs and
-- recreates everything — it is for a fresh database, not a live one. This is the
-- script for a database with data in it. Equivalent to migrations/0016_create_auth_tables.ts,
-- for deployments that apply SQL by hand rather than running the migrator.)
--
--   psql "$DATABASE_URL" -f docs/add-auth.sql
--
-- Then create the first account (it must be an admin, or no one can create the second):
--
--   npm run create-user -- you@example.com 'a long passphrase' --name "You" --admin
--
-- Adjust the schema below if yours is not `lakeshore` (it must match DB_SCHEMA).
-- ============================================================================

SET search_path TO lakeshore, public;

-- ─────────────────────────────────────────────────────────────
-- app_user — who can sign in.
--
-- password_hash is a self-describing scrypt string: the cost parameters travel with
-- each hash (api/src/lib/password.ts), so they can be raised later without
-- invalidating a single existing row.
-- ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS app_user (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email         varchar(320) NOT NULL,        -- 64 local + @ + 255 domain
  password_hash text NOT NULL,
  name          varchar(255),
  roles         text[] NOT NULL DEFAULT '{}',
  -- Disabling beats deleting: it kills the login without orphaning what the user made.
  -- The guard re-checks it on every request, so it takes effect immediately.
  is_active     boolean NOT NULL DEFAULT true,
  last_login_at timestamptz,
  -- Where that last sign-in came from (see docs/add-last-login-ip.sql, which adds this to a
  -- database that already ran an earlier version of this script).
  last_login_ip varchar(64),
  created_at    timestamptz NOT NULL DEFAULT now(),
  updated_at    timestamptz NOT NULL DEFAULT now()
);

-- On lower(email), not email: otherwise Ann@x.com and ann@x.com are two accounts, and
-- which one you get at sign-in depends on how you typed it.
CREATE UNIQUE INDEX IF NOT EXISTS idx_app_user_email ON app_user (lower(email));

-- ─────────────────────────────────────────────────────────────
-- auth_session — the live sessions.
--
-- A session is a ROW, and that is the whole point: it can be revoked. Signing out,
-- disabling an account or changing a password takes effect on the next request. A JWT
-- cannot do that — it stays valid until it expires, no matter what the server wants.
--
-- token_hash is the SHA-256 of the 32 random bytes the browser holds in its cookie. The
-- plaintext is never stored, so a dump of this table yields nothing replayable as a login.
-- ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS auth_session (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- Deleting a user must take their live sessions with them, or they stay signed in.
  user_id      bigint NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,
  token_hash   varchar(64) NOT NULL UNIQUE,
  expires_at   timestamptz NOT NULL,
  last_seen_at timestamptz NOT NULL DEFAULT now(),
  user_agent   text,
  ip           varchar(64),
  created_at   timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_auth_session_user    ON auth_session (user_id);     -- "sign out everywhere"
CREATE INDEX IF NOT EXISTS idx_auth_session_expires ON auth_session (expires_at);  -- sweep of expired rows

-- Keep updated_at fresh (Postgres has no built-in "on update"). The function is defined by
-- schema-redesign.sql; create the trigger only if it exists, so this script stands alone.
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM pg_proc p
      JOIN pg_namespace n ON n.oid = p.pronamespace
     WHERE p.proname = 'set_updated_at' AND n.nspname = 'lakeshore'
  ) THEN
    DROP TRIGGER IF EXISTS trg_app_user_updated ON app_user;
    CREATE TRIGGER trg_app_user_updated BEFORE UPDATE ON app_user
      FOR EACH ROW EXECUTE PROCEDURE lakeshore.set_updated_at();
  END IF;
END
$$;
