-- ============================================================================
-- NameSync — add the email one-time-code login to an EXISTING database
-- ============================================================================
-- Companion to add-auth.sql. Purely additive and fully idempotent: it creates one
-- table and its indexes, drops nothing, and touches no existing row. Running it twice
-- is a no-op. Requires add-auth.sql to have run first (it references app_user).
--
--   psql "$DATABASE_URL" -f docs/add-otp-login.sql
--
-- Adjust the schema below if yours is not `lakeshore` (it must match DB_SCHEMA).
-- ============================================================================

SET search_path TO lakeshore, public;

-- ─────────────────────────────────────────────────────────────
-- email_otp — a one-time code emailed to a user during sign-in.
--
-- code_hash is a scrypt hash of the digits, never the digits (api/src/lib/password.ts). A
-- 6-digit code is instantly reversible from a fast hash, so it is protected exactly like a
-- password: a dump of this table yields nothing that can be replayed as a login.
--
-- The code is single-use and short-lived. consumed_at is stamped on first correct use;
-- `attempts` counts wrong guesses and the code is refused once it passes OTP_MAX_ATTEMPTS;
-- expires_at is enforced in SQL by the lookup. See api/src/services/otp-auth.service.ts.
-- ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS email_otp (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- Deleting a user takes their pending codes with them.
  user_id     bigint NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,
  purpose     varchar(32) NOT NULL DEFAULT 'login',
  code_hash   text NOT NULL,
  expires_at  timestamptz NOT NULL,
  consumed_at timestamptz,
  attempts    integer NOT NULL DEFAULT 0,
  ip          varchar(64),
  user_agent  text,
  created_at  timestamptz NOT NULL DEFAULT now()
);

-- "invalidate this user's other pending codes", and the sweep of expired rows.
CREATE INDEX IF NOT EXISTS idx_email_otp_user    ON email_otp (user_id);
CREATE INDEX IF NOT EXISTS idx_email_otp_expires ON email_otp (expires_at);
