-- ============================================================================
-- NameSync — target schema for the `lakeshore` Postgres schema (onewebdb)
-- ============================================================================
-- Clean cutover: no data to preserve. Drops the GraphML-draft tables and
-- creates the redesign. Every object is schema-qualified (lakeshore.*) so it
-- never depends on the session search_path.
--
-- Model: append-only ("stacking"). Every uploaded row is stored as-is, tagged
-- with the upload that added it (upload_id FK). Uploads are immutable snapshots;
-- no cross-upload dedup, so a rollback is simply "delete this upload's rows".
--   * comparison / comparison_result split the run (header) from its scored
--     matches (rows) — the header is the durable home for status + expected_batches.
--
-- Keys: bigint identity (matches the existing batch_file.id bigserial / int8 style).
-- Types: timestamptz, jsonb, text+CHECK "enums".
-- ============================================================================

-- The schema already exists; uncomment if running somewhere fresh:
-- CREATE SCHEMA IF NOT EXISTS lakeshore;

-- Verify what's actually here before dropping:
--   SELECT tablename FROM pg_tables WHERE schemaname = 'lakeshore';

-- ── Drop tables so the whole script is re-runnable (no data) ────────────────
-- Redesign tables (in case a prior run of this script partially applied):
DROP TABLE IF EXISTS lakeshore.comparison_result CASCADE;
DROP TABLE IF EXISTS lakeshore.comparison        CASCADE;
DROP TABLE IF EXISTS lakeshore.company_contact   CASCADE;
DROP TABLE IF EXISTS lakeshore.friend            CASCADE;
DROP TABLE IF EXISTS lakeshore.upload            CASCADE;
-- Original GraphML-draft tables:
DROP TABLE IF EXISTS lakeshore.batch_file             CASCADE;
DROP TABLE IF EXISTS lakeshore.social_media_friends   CASCADE;
DROP TABLE IF EXISTS lakeshore.upload_record          CASCADE;
-- Superseded membership tables (from the earlier dedup design):
DROP TABLE IF EXISTS lakeshore.friend_upload          CASCADE;
DROP TABLE IF EXISTS lakeshore.company_contact_upload CASCADE;
-- Kept-as-is audit/history tables:
DROP TABLE IF EXISTS lakeshore.history_sessions       CASCADE;
DROP TABLE IF EXISTS lakeshore.upload_history         CASCADE;
-- Database console:
DROP TABLE IF EXISTS lakeshore.saved_query            CASCADE;

-- Auth (auth_session first — it holds the FK into app_user):
DROP TABLE IF EXISTS lakeshore.auth_session           CASCADE;
DROP TABLE IF EXISTS lakeshore.app_user               CASCADE;


-- ─────────────────────────────────────────────────────────────
-- upload: one import event (a single company CSV OR a single social JSON).
-- Roll-back-able. (Replaces upload_record + batch_file.)
-- ─────────────────────────────────────────────────────────────
CREATE TABLE lakeshore.upload (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name              varchar(255),
  kind              text NOT NULL CHECK (kind IN ('company','social')),
  source            varchar(100),                            -- social: 'facebook'|'linkedin'|…; company: NULL
  status            text NOT NULL DEFAULT 'processing'
                      CHECK (status IN ('pending','processing','pending_webhook',
                                        'completed','failed','rolled_back')),
  mode              varchar(20),                             -- known values: 'fresh' | 'continue'
  uploaded_by       varchar(255),
  total_records     integer NOT NULL DEFAULT 0,             -- rows this import added
  duplicate_records integer NOT NULL DEFAULT 0,             -- informational (0 under stacking)
  -- The run this import started (EXTERNAL_MATCHER only; NULL otherwise — an import made with
  -- the internal matcher starts no run). The foreign key is added further down, once
  -- `comparison` exists: this table is declared before it.
  comparison_id     bigint,
  created_at        timestamptz NOT NULL DEFAULT now(),
  updated_at        timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_upload_created ON lakeshore.upload (created_at DESC);
CREATE INDEX idx_upload_kind    ON lakeshore.upload (kind);
CREATE INDEX idx_upload_status  ON lakeshore.upload (status);


-- ─────────────────────────────────────────────────────────────
-- friend: social contacts, one row per uploaded line (append-only). Belongs to
-- exactly one upload; rolling back that upload deletes its rows (ON DELETE CASCADE).
-- ─────────────────────────────────────────────────────────────
-- The `*_clean` columns hold the name with titles, suffixes, nicknames and middle tokens
-- stripped (api/src/services/name-cleaner.service.ts), written at import next to — never
-- over — the raw name. Matching, dedup and display read clean; the raw column is the
-- record of what the file actually said, so a bad rule is a backfill, not a re-upload.
CREATE TABLE lakeshore.friend (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  upload_id         bigint NOT NULL REFERENCES lakeshore.upload(id) ON DELETE CASCADE,
  source            varchar(100) NOT NULL,                  -- 'facebook' | 'linkedin' | …
  friend_name       varchar(255),                           -- as uploaded
  friend_name_clean varchar(255),                           -- derived; NULL only if raw is
  source_timestamp  timestamptz,
  fetched           boolean NOT NULL DEFAULT false,         -- through a completed comparison ("old")
  -- The external workflow's verdict on this row: 'processing' → 'match' | 'unmatch'.
  -- No CHECK on purpose: an unexpected value must not fail the workflow's write, and the
  -- app reads anything other than 'processing' as "finished". See docs/EXTERNAL-MATCHER.md.
  status            text NOT NULL DEFAULT 'processing',
  created_at        timestamptz NOT NULL DEFAULT now(),
  updated_at        timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_friend_upload     ON lakeshore.friend (upload_id);       -- rollback / by-upload
CREATE INDEX idx_friend_name       ON lakeshore.friend (friend_name);     -- results lookup
CREATE INDEX idx_friend_name_clean ON lakeshore.friend (friend_name_clean); -- matcher + dedup
CREATE INDEX idx_friend_fetched    ON lakeshore.friend (fetched);         -- stats
-- "Is this upload still working?" — the poll that decides an import is done.
CREATE INDEX idx_friend_upload_status ON lakeshore.friend (upload_id, status);


-- ─────────────────────────────────────────────────────────────
-- company_contact: company people, append-only, one upload per row.
-- ─────────────────────────────────────────────────────────────
-- Same raw/clean pair as `friend`, once per script. company_name has no clean twin: it is
-- only ever grouped and matched exactly, and "Mr" inside a company's name is its name.
CREATE TABLE lakeshore.company_contact (
  id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  upload_id            bigint NOT NULL REFERENCES lakeshore.upload(id) ON DELETE CASCADE,
  company_name         varchar(255),
  person_name_th       varchar(255),                        -- as uploaded
  person_name_th_clean varchar(255),                        -- derived; NULL only if raw is
  person_name_en       varchar(255),                        -- as uploaded
  person_name_en_clean varchar(255),                        -- derived; NULL only if raw is
  fetched              boolean NOT NULL DEFAULT false,
  -- Same as friend.status — the workflow's verdict on this row.
  status               text NOT NULL DEFAULT 'processing',
  created_at           timestamptz NOT NULL DEFAULT now(),
  updated_at           timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_company_contact_upload  ON lakeshore.company_contact (upload_id);
CREATE INDEX idx_company_contact_company ON lakeshore.company_contact (company_name);
CREATE INDEX idx_company_contact_fetched ON lakeshore.company_contact (fetched);
CREATE INDEX idx_company_contact_upload_status ON lakeshore.company_contact (upload_id, status);
-- The matcher reads (company_name → both clean names) for every compare run.
CREATE INDEX idx_company_contact_clean   ON lakeshore.company_contact (company_name, person_name_th_clean, person_name_en_clean);


-- ─────────────────────────────────────────────────────────────
-- comparison: one compare run (the header). selected_company is what the run
-- matched against; expected_batches is the durable denominator for progress.
-- ─────────────────────────────────────────────────────────────
CREATE TABLE lakeshore.comparison (
  id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name             varchar(255),
  selected_company varchar(255),
  source           varchar(100),                            -- social source compared
  status           text NOT NULL DEFAULT 'processing'
                     CHECK (status IN ('pending','processing','completed','failed')),
  expected_batches integer,                                 -- total declared by the matcher (0/NULL = unknown)
  created_at       timestamptz NOT NULL DEFAULT now(),
  updated_at       timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_comparison_created ON lakeshore.comparison (created_at DESC);

-- comparison_result: the scored matches, appended one batch at a time.
CREATE TABLE lakeshore.comparison_result (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  comparison_id  bigint NOT NULL REFERENCES lakeshore.comparison(id) ON DELETE CASCADE,
  friend_name    varchar(255),
  person_name_en varchar(255),
  person_name_th varchar(255),
  matching_score real,
  batch_number   integer,
  is_complete    boolean NOT NULL DEFAULT false,
  upload_name    varchar(255),                              -- connected uploader, when matcher provides it
  extra          jsonb,                                     -- non-standard matcher fields
  created_at     timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_comparison_result_comparison ON lakeshore.comparison_result (comparison_id);
-- Serves both the distinct-batch progress count and batch-level idempotency.
CREATE INDEX idx_comparison_result_batch ON lakeshore.comparison_result (comparison_id, batch_number);

-- upload.comparison_id → comparison. Declared here rather than on the column, because
-- `upload` is created before `comparison` is.
ALTER TABLE lakeshore.upload
  ADD CONSTRAINT upload_comparison_id_fkey
  FOREIGN KEY (comparison_id) REFERENCES lakeshore.comparison(id) ON DELETE SET NULL;


-- ─────────────────────────────────────────────────────────────
-- history_sessions: REMOVED. "Past runs" lists the runs themselves (GET /api/comparisons).
-- comparison_result stores names and scores as text with no FK back to friend /
-- company_contact, so a finished run is already immutable — there was nothing a saved
-- snapshot could protect against, only a second copy of the same data in a second shape.
-- (The DROP above is what removes it from a database that already has it.)
-- ─────────────────────────────────────────────────────────────


-- ─────────────────────────────────────────────────────────────
-- saved_query: a named, re-runnable query from the Database console.
--   kind='sql'      sql_text holds a read-only SELECT typed into the SQL editor
--   kind='builder'  spec holds the visual builder's {table, filters, sort} as JSON
-- created_by is the app_user id of whoever saved it.
-- (Mirrored by migrations/0014_create_saved_query.ts — keep the two in step.)
-- ─────────────────────────────────────────────────────────────
CREATE TABLE lakeshore.saved_query (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       varchar(255) NOT NULL,
  kind       text NOT NULL CHECK (kind IN ('sql','builder')),
  sql_text   text,
  spec       jsonb,
  created_by varchar(255),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_saved_query_created ON lakeshore.saved_query (created_at DESC);


-- ─────────────────────────────────────────────────────────────
-- app_user / auth_session: authentication.
--
-- NameSync used to sit behind a website that logged the user in and handed over a JWT —
-- it only ever *verified* one. It now owns the whole flow, which is what these two tables
-- are for. password_hash is a self-describing scrypt string (api/src/lib/password.ts);
-- token_hash is the SHA-256 of the session token the browser holds, so a dump of
-- auth_session yields nothing that can be replayed as a login.
--
-- A session is a ROW, which is the point: it can be revoked. A JWT cannot be.
-- (Mirrored by migrations/0015_create_auth_tables.ts — keep the two in step.)
-- ─────────────────────────────────────────────────────────────
CREATE TABLE lakeshore.app_user (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email         varchar(320) NOT NULL,        -- 64 local + @ + 255 domain
  password_hash text NOT NULL,
  name          varchar(255),
  roles         text[] NOT NULL DEFAULT '{}',
  is_active     boolean NOT NULL DEFAULT true,
  last_login_at timestamptz,
  created_at    timestamptz NOT NULL DEFAULT now(),
  updated_at    timestamptz NOT NULL DEFAULT now()
);
-- On lower(email), not email: otherwise Ann@x.com and ann@x.com are two accounts, and
-- which one you get at login depends on how you typed it.
CREATE UNIQUE INDEX idx_app_user_email ON lakeshore.app_user (lower(email));

CREATE TABLE lakeshore.auth_session (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- Deleting a user must take their live sessions with them, or they stay signed in.
  user_id      bigint NOT NULL REFERENCES lakeshore.app_user (id) ON DELETE CASCADE,
  token_hash   varchar(64) NOT NULL UNIQUE,   -- sha256 hex of the token the browser holds
  expires_at   timestamptz NOT NULL,
  last_seen_at timestamptz NOT NULL DEFAULT now(),
  user_agent   text,
  ip           varchar(64),
  created_at   timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_auth_session_user    ON lakeshore.auth_session (user_id);     -- "sign out everywhere"
CREATE INDEX idx_auth_session_expires ON lakeshore.auth_session (expires_at);  -- sweep of expired rows


-- ============================================================================
-- Optional: keep updated_at fresh (Postgres has no built-in "on update").
-- Uses EXECUTE PROCEDURE (not EXECUTE FUNCTION) so it works on Postgres 10;
-- PROCEDURE is still accepted on every newer version too.
-- ============================================================================
CREATE OR REPLACE FUNCTION lakeshore.set_updated_at() RETURNS trigger AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_upload_updated          ON lakeshore.upload;
CREATE TRIGGER trg_upload_updated          BEFORE UPDATE ON lakeshore.upload
  FOR EACH ROW EXECUTE PROCEDURE lakeshore.set_updated_at();
DROP TRIGGER IF EXISTS trg_friend_updated          ON lakeshore.friend;
CREATE TRIGGER trg_friend_updated          BEFORE UPDATE ON lakeshore.friend
  FOR EACH ROW EXECUTE PROCEDURE lakeshore.set_updated_at();
DROP TRIGGER IF EXISTS trg_company_contact_updated ON lakeshore.company_contact;
CREATE TRIGGER trg_company_contact_updated BEFORE UPDATE ON lakeshore.company_contact
  FOR EACH ROW EXECUTE PROCEDURE lakeshore.set_updated_at();
DROP TRIGGER IF EXISTS trg_comparison_updated      ON lakeshore.comparison;
CREATE TRIGGER trg_comparison_updated      BEFORE UPDATE ON lakeshore.comparison
  FOR EACH ROW EXECUTE PROCEDURE lakeshore.set_updated_at();
DROP TRIGGER IF EXISTS trg_saved_query_updated     ON lakeshore.saved_query;
CREATE TRIGGER trg_saved_query_updated     BEFORE UPDATE ON lakeshore.saved_query
  FOR EACH ROW EXECUTE PROCEDURE lakeshore.set_updated_at();
DROP TRIGGER IF EXISTS trg_app_user_updated        ON lakeshore.app_user;
CREATE TRIGGER trg_app_user_updated        BEFORE UPDATE ON lakeshore.app_user
  FOR EACH ROW EXECUTE PROCEDURE lakeshore.set_updated_at();


-- ============================================================================
-- Reference queries (how the app uses the shape)
-- ============================================================================

-- Rollback an import: just delete its rows (upload_id FK). No orphan check needed.
--   DELETE FROM lakeshore.friend          WHERE upload_id = :uploadId;   -- (or company_contact)
--   UPDATE lakeshore.upload SET status = 'rolled_back' WHERE id = :uploadId;

-- Compare-run progress (numerator computed, never stored → can't drift):
--   SELECT count(DISTINCT batch_number) AS received_batches
--     FROM lakeshore.comparison_result WHERE comparison_id = :cmpId;
--   -- complete when received_batches >= comparison.expected_batches (and > 0)

-- On completion, mark the "new" rows "old":
--   UPDATE lakeshore.friend          SET fetched = true WHERE fetched = false;
--   UPDATE lakeshore.company_contact SET fetched = true WHERE fetched = false;
