  -- ============================================================================
  -- Network Intel — target schema for the `lakeshore` Postgres schema (onewebdb)
  -- ============================================================================
  -- Clean cutover: no data to preserve. Drops the GraphML-draft tables and
  -- creates the redesign. Every object is schema-qualified (lakeshore.*) so it
  -- never depends on the session search_path.
  --
  -- Model: append-only ("stacking"). Every uploaded row is stored as-is, tagged
  -- with the upload that added it (upload_id FK). Uploads are immutable snapshots;
  -- no cross-upload dedup, so a rollback is simply "delete this upload's rows".
  --   * comparison / comparison_result split the run (header) from its scored
  --     matches (rows) — the header is the durable home for status + expected_batches.
  --
  -- Keys: bigint identity (int8).
  -- Types: timestamptz, jsonb, text+CHECK "enums".
  -- ============================================================================

  -- The schema already exists; uncomment if running somewhere fresh:
  -- CREATE SCHEMA IF NOT EXISTS lakeshore;

  -- Verify what's actually here before dropping:
  --   SELECT tablename FROM pg_tables WHERE schemaname = 'lakeshore';

  -- ── Drop tables so the whole script is re-runnable (no data) ────────────────
  -- Redesign tables (in case a prior run of this script partially applied):
  DROP TABLE IF EXISTS lakeshore.comparison_result CASCADE;
  DROP TABLE IF EXISTS lakeshore.comparison        CASCADE;
  DROP TABLE IF EXISTS lakeshore.company_contact   CASCADE;
  DROP TABLE IF EXISTS lakeshore.friend            CASCADE;
  DROP TABLE IF EXISTS lakeshore.upload            CASCADE;
  DROP TABLE IF EXISTS lakeshore.upload_source     CASCADE;
  -- Original GraphML-draft tables:
  DROP TABLE IF EXISTS lakeshore.batch_file             CASCADE;
  DROP TABLE IF EXISTS lakeshore.social_media_friends   CASCADE;
  DROP TABLE IF EXISTS lakeshore.upload_record          CASCADE;
  -- Superseded membership tables (from the earlier dedup design):
  DROP TABLE IF EXISTS lakeshore.friend_upload          CASCADE;
  DROP TABLE IF EXISTS lakeshore.company_contact_upload CASCADE;
  -- Kept-as-is audit/history tables:
  DROP TABLE IF EXISTS lakeshore.history_sessions       CASCADE;
  DROP TABLE IF EXISTS lakeshore.upload_history         CASCADE;
  -- Database console:
  DROP TABLE IF EXISTS lakeshore.saved_query            CASCADE;

  -- Auth (children first — they hold the FK into app_user):
  DROP TABLE IF EXISTS lakeshore.email_otp              CASCADE;
  DROP TABLE IF EXISTS lakeshore.auth_session           CASCADE;
  DROP TABLE IF EXISTS lakeshore.app_user               CASCADE;


  -- ─────────────────────────────────────────────────────────────
  -- upload: one import event (a single company CSV OR a single social JSON).
  -- Roll-back-able. (Replaces the GraphML-draft upload_record + batch_file pair.)
  -- ─────────────────────────────────────────────────────────────
  CREATE TABLE lakeshore.upload (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name              varchar(255),
    kind              text NOT NULL CHECK (kind IN ('company','social')),
    -- Where the data came from, and the app's "type" axis: 'facebook' | 'linkedin' |
    -- 'business card' | …; NULL for a company import. The pick-list lives in
    -- lakeshore.upload_source (seeded + user-extensible); this column is free text and is
    -- deliberately not constrained by an FK to it — see that table.
    source            varchar(100),
    status            text NOT NULL DEFAULT 'processing'
                        CHECK (status IN ('pending','processing','pending_webhook',
                                          'completed','failed','rolled_back')),
    mode              varchar(20),                             -- known values: 'fresh' | 'continue'
    -- Who PERFORMED the import. Narrowed on 2026-07-27: it used to mean "the relationship
    -- owner for this import", which conflated two people who are usually but not always the
    -- same — an assistant importing on a salesperson's behalf is the case that forced them
    -- apart. Whose relationship a friend is now lives on `friend.relationship_owner`, per row.
    -- Defaulted from the signed-in user, overridable at import.
    uploaded_by       varchar(255),
    total_records     integer NOT NULL DEFAULT 0,             -- rows this import added
    duplicate_records integer NOT NULL DEFAULT 0,             -- informational (0 under stacking)
    -- The run this import started (EXTERNAL_MATCHER only; NULL otherwise — an import made with
    -- the internal matcher starts no run). The foreign key is added further down, once
    -- `comparison` exists: this table is declared before it.
    comparison_id     bigint,
    created_at        timestamptz NOT NULL DEFAULT now(),
    updated_at        timestamptz NOT NULL DEFAULT now()
  );
  CREATE INDEX idx_upload_created ON lakeshore.upload (created_at DESC);
  CREATE INDEX idx_upload_kind    ON lakeshore.upload (kind);
  CREATE INDEX idx_upload_status  ON lakeshore.upload (status);


  -- ─────────────────────────────────────────────────────────────
  -- upload_source: the pick-list behind an import's "type" — where the data came from.
  -- ─────────────────────────────────────────────────────────────
  -- The VALUES live in upload.source / friend.source, which already held this vocabulary
  -- ('facebook' | 'linkedin'). This table exists for the two things a distinct-values query
  -- over those columns cannot do: seed an empty database (so the picker offers the three on
  -- day one, before any import has used them), and let a user add a fourth that persists for
  -- the next user without a deploy.
  --
  -- NOT referenced by a foreign key from upload.source / friend.source, deliberately. Those
  -- columns are also written by the Database console, and an FK would turn a value this table
  -- has not heard of into a failed write on a row that is otherwise perfectly good — the same
  -- stance friend.status takes, for the same reason. This table constrains the dropdown, not
  -- the column. The picker unions it with the distinct values actually in use, so a value
  -- written around it still appears in the list it is plainly a member of.
  CREATE TABLE lakeshore.upload_source (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    value      varchar(100) NOT NULL,                   -- what gets stored in upload.source
    label      varchar(100) NOT NULL,                   -- how it reads in the picker
    created_by varchar(255),
    created_at timestamptz NOT NULL DEFAULT now()
  );
  CREATE UNIQUE INDEX idx_upload_source_value ON lakeshore.upload_source (lower(value));

  -- The three below are a starting vocabulary, not a protected one: every row here is deletable
  -- through the API, including these. There used to be an `is_seeded` flag that made them
  -- undeletable, on the grounds that the import path names 'facebook' in code. It bought less
  -- than it looked like: no foreign key points at these values, so deleting one cannot fail a
  -- write, and `UploadSourceModel.list` unions this table with the values actually in use — so
  -- a deleted 'facebook' keeps appearing in the picker for as long as any import carries it.
  -- The flag only bit on a database where nothing had used the value, which is a database where
  -- removing the option is the harmless thing to do.
  INSERT INTO lakeshore.upload_source (value, label)
  VALUES ('business card', 'Business card'),
         ('facebook',      'Facebook'),
         ('linkedin',      'LinkedIn');


  -- ─────────────────────────────────────────────────────────────
  -- friend: social contacts, one row per uploaded line (append-only). Belongs to
  -- exactly one upload; rolling back that upload deletes its rows (ON DELETE CASCADE).
  -- ─────────────────────────────────────────────────────────────
  -- Names are stored ALREADY CLEANED and lower-cased — titles, suffixes and nicknames stripped at
  -- import (api/src/services/name-cleaner.service.ts). There is no raw twin: the file's own
  -- spelling is shown in the import preview and then not kept. Which is why the cleaner no longer
  -- drops middle tokens — that rule was only safe while the raw name survived to undo it from.
  -- Matching, dedup and display all read these columns directly.
  --
  -- The pre-2026-07-28 single `friend_name` is GONE (2026-07-28b-drop-friend-name.sql). It was kept
  -- through phase 1 of the bilingual migration "so a rollback stays available", and that reason
  -- expired on the day it was written: nothing wrote the column after the split, so every row
  -- created since had NULL in it and the rollback it protected could not have worked. It was
  -- carrying two indexes for nothing by the time it went.
  CREATE TABLE lakeshore.friend (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    upload_id         bigint NOT NULL REFERENCES lakeshore.upload(id) ON DELETE CASCADE,
    source            varchar(100) NOT NULL,                  -- 'facebook' | 'linkedin' | 'business card' | …
    -- A column per language, symmetric with company_contact — both cleaned + lower-cased at
    -- import, so they compare directly against person_name_en / person_name_th.
    --
    -- The asymmetry that used to be here was defended as being in the DATA: a social export
    -- carries one `name` field, so a second column would have meant script-detecting the one
    -- stored name and filing it under a label — inventing no information. That holds for a
    -- Facebook export and fails for a business card, which prints both spellings and which
    -- `upload_source` seeds as a first-class import type. The information was arriving in the
    -- files; the parser was discarding it.
    --
    -- AT LEAST ONE IS NON-NULL on any stored row. "No usable name at all" is the only condition
    -- the import gate drops on, and it must NEVER become "no name in the run's language" — a
    -- run's mode decides what is SCORED, never what is STORED. Uploading a mixed file under
    -- `th_full` stores every friend, including the English-only ones; the language test lives at
    -- match time in MatcherService.run, not in the parser or the import gate.
    friend_name_en    varchar(255),
    friend_name_th    varchar(255),
    -- Whose relationship this is — the person to go and ask for the introduction, which is
    -- the question the whole product exists to answer.
    --
    -- Per FRIEND, not per upload, because one export can hold several people's contacts: a
    -- friends file may carry its own owner column, and when it does each row's owner is read
    -- off that row. When it doesn't, one typed value is applied to every row of the import.
    -- This was derived by joining `upload.uploaded_by` until 2026-07-27, which could only
    -- ever describe a file as having one owner.
    --
    -- Cleaned like a person's name (titles/nicknames/suffixes stripped) but NOT lower-cased —
    -- see cleanOwnerName in services/name-cleaner.service.ts. An owner is grouped
    -- case-insensitively and displayed as written, exactly like company_name, because this
    -- is the string the UI puts in front of someone as "go ask this person".
    relationship_owner varchar(255),
    -- WHICH PERSON THIS ROW IS ABOUT — one uuid shared by every row that is the same person.
    --
    -- Imports STACK: every row of every import is inserted under that import's own upload_id,
    -- because the external workflow selects what to match with `WHERE upload_id = :session_id`
    -- and cannot see rows filed under an earlier import. Dedup therefore happens at READ time,
    -- on this column, rather than at write time by refusing the insert.
    --
    -- Assigned at import by the same matching that used to decide whether to skip the row (same
    -- owner, either spelling equal — the two indexes below are its probe). The DEFAULT covers the
    -- Database console, which writes this table directly: a hand-added row is its own person,
    -- where NULL would fold every such row into one.
    person_key        uuid NOT NULL DEFAULT gen_random_uuid(),
    -- The external workflow's verdict on this row: 'processing' → 'match' | 'unmatch'.
    -- No CHECK on purpose: an unexpected value must not fail the workflow's write, and the
    -- app reads anything other than 'pending'/'processing' as "finished". See
    -- docs/EXTERNAL-MATCHER.md and extensions/contract/src/row-status.ts.
    status            text NOT NULL DEFAULT 'processing',
    created_at        timestamptz NOT NULL DEFAULT now(),
    updated_at        timestamptz NOT NULL DEFAULT now()
  );
  CREATE INDEX idx_friend_upload     ON lakeshore.friend (upload_id);       -- rollback / by-upload
  -- "Is this upload still working?" — the poll that decides an import is done.
  CREATE INDEX idx_friend_upload_status ON lakeshore.friend (upload_id, status);
  -- THE IDENTITY PROBE: (owner, name), once per spelling. `mergeUpload` probes an incoming row
  -- against BOTH, because a row matching an existing one on the same owner and EITHER non-null
  -- spelling is the same friend — that is what lets it inherit their `person_key` instead of being
  -- filed as a second person.
  --
  -- It used to be the DEDUP key, and decided whether to insert at all. It no longer does: imports
  -- stack, and the same match now assigns identity rather than refusing the row. Same probe, same
  -- indexes, different consequence.
  --
  -- Case-folded on the owner because every reader of an owner name folds it, and a key that saw
  -- "Alex" and "alex" as two rosters while the Overview showed them as one is the inconsistency
  -- this replaced.
  --
  -- These two ARE the key. A third, `idx_friend_owner_name` over the old single `friend_name`, was
  -- still labelled "the dedup key" here after the split had moved every probe onto the pair below —
  -- a stale comment describing an index nothing used. It went with the column.
  CREATE INDEX idx_friend_owner_name_en ON lakeshore.friend (lower(relationship_owner), friend_name_en);
  CREATE INDEX idx_friend_owner_name_th ON lakeshore.friend (lower(relationship_owner), friend_name_th);
  -- The roster queries — Overview's "whose friends", the Uploaders tab — group by owner alone.
  CREATE INDEX idx_friend_owner      ON lakeshore.friend (lower(relationship_owner));
  -- The run's source filter (comparison.sources → FriendModel.findAllForMatching) and the counts
  -- the source picker shows beside each option. Folded, because the picker stores 'facebook' and
  -- the Database console can write 'Facebook' into the same column.
  CREATE INDEX idx_friend_source     ON lakeshore.friend (lower(source));
  -- The read-time fold. On the hot path of every Network query, over a table that now grows with
  -- each re-import rather than holding one row per person.
  CREATE INDEX idx_friend_person_key    ON lakeshore.friend (person_key);
  CREATE INDEX idx_friend_person_recent ON lakeshore.friend (person_key, created_at DESC, id DESC);


  -- ─────────────────────────────────────────────────────────────
  -- company_contact: company people, append-only, one upload per row.
  -- ─────────────────────────────────────────────────────────────
  -- Person names are cleaned + lower-cased at import and stored once, exactly as in `friend`.
  -- company_name is the exception and is NOT cleaned the same way: it is only ever grouped and
  -- matched exactly, and "Mr" inside a company's name is its name. It is tidied (whitespace,
  -- invisible characters) and keeps its case, so every reader comparing one folds case itself.
  CREATE TABLE lakeshore.company_contact (
    id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    upload_id            bigint NOT NULL REFERENCES lakeshore.upload(id) ON DELETE CASCADE,
    company_name         varchar(255),                        -- tidied only; case-preserving
    person_name_th       varchar(255),                        -- cleaned + lower-cased at import
    person_name_en       varchar(255),                        -- cleaned + lower-cased at import
    -- Which contact this row is about — the company-side twin of friend.person_key, same stacking
    -- rationale. Scoped WITHIN a company (the same name at two employers is two contacts, not a
    -- duplicate) and linked on EITHER spelling, which the old tuple key could not do: under it,
    -- the same person imported once with only the English column mapped and again with only the
    -- Thai column was two rows, and every count saw two people.
    person_key           uuid NOT NULL DEFAULT gen_random_uuid(),
    -- Same as friend.status — the workflow's verdict on this row.
    status               text NOT NULL DEFAULT 'processing',
    created_at           timestamptz NOT NULL DEFAULT now(),
    updated_at           timestamptz NOT NULL DEFAULT now()
  );
  CREATE INDEX idx_company_contact_upload  ON lakeshore.company_contact (upload_id);
  CREATE INDEX idx_company_contact_company ON lakeshore.company_contact (company_name);
  CREATE INDEX idx_company_contact_upload_status ON lakeshore.company_contact (upload_id, status);
  -- The matcher reads (company_name → both person names) for every compare run.
  CREATE INDEX idx_company_contact_names   ON lakeshore.company_contact (company_name, person_name_th, person_name_en);
  -- The identity probe, one per spelling — the composite above cannot serve a lookup on ONE name
  -- column, which is exactly what either-spelling linking needs.
  CREATE INDEX idx_company_contact_company_en ON lakeshore.company_contact (lower(company_name), person_name_en);
  CREATE INDEX idx_company_contact_company_th ON lakeshore.company_contact (lower(company_name), person_name_th);
  -- The read-time fold — see the friend twins.
  CREATE INDEX idx_company_contact_person_key    ON lakeshore.company_contact (person_key);
  CREATE INDEX idx_company_contact_person_recent ON lakeshore.company_contact (person_key, created_at DESC, id DESC);


  -- ─────────────────────────────────────────────────────────────
  -- friend_current / company_contact_current: one row per PERSON.
  -- ─────────────────────────────────────────────────────────────
  -- Imports stack, so the tables above hold one row per (person, import). These fold them back.
  --
  -- WHICH READS USE THESE, AND WHICH MUST NOT — the rule the whole design rests on:
  --
  --   · A question about PEOPLE — how many friends are on file, who is in a roster, the company
  --     picker, the per-source counts — reads the view. Stacked copies are one person.
  --   · A question about an IMPORT or a RUN — progress, an upload's own rows, the webhook
  --     payload, rollback — reads the raw table. Those questions are ABOUT the copies, and
  --     folding them would break progress counting outright: a run's denominator IS its rows.
  --
  -- Spellings are COALESCED across the person's rows, not taken from the newest row whole. This is
  -- what replaces enrichment. A friend imported in English and later in Thai is two rows with one
  -- spelling each; taking the newest row would show them as Thai-only and lose the English name an
  -- `en` run still matches on. Non-nulls sort first, so each language resolves to a row that had one.
  --
  -- Among non-nulls the OLDEST wins, reproducing the fill-only rule this replaces: an import could
  -- fill a NULL spelling and never change a stored one, so the first spelling recorded is the one
  -- that stuck. Newest-first would invert that and let a later file silently overwrite a name.
  --
  -- status / upload_id are the NEWEST row's and describe that row, not the person. Anything that
  -- genuinely cares is run-scoped and reads the raw table.
  CREATE VIEW lakeshore.friend_current AS
  SELECT
    f.person_key,
    -- The person's FIRST row, not their latest: stable across re-imports, and consistent with the
    -- name columns below, which also resolve oldest-first.
    min(f.id)                                                                         AS id,
    (array_agg(f.source ORDER BY f.created_at DESC, f.id DESC))[1]                    AS source,
    -- Constant within the group (the owner is half the identity); newest for its CAPITALISATION,
    -- which is display text a later import may have spelled better.
    (array_agg(f.relationship_owner ORDER BY f.created_at DESC, f.id DESC))[1]        AS relationship_owner,
    (array_agg(f.friend_name_en
               ORDER BY (f.friend_name_en IS NULL), f.created_at ASC, f.id ASC))[1] AS friend_name_en,
    (array_agg(f.friend_name_th
               ORDER BY (f.friend_name_th IS NULL), f.created_at ASC, f.id ASC))[1] AS friend_name_th,
    min(f.created_at)                                                                 AS created_at,
    max(f.updated_at)                                                                 AS updated_at
  FROM lakeshore.friend f
  GROUP BY f.person_key;

  CREATE VIEW lakeshore.company_contact_current AS
  SELECT
    c.person_key,
    min(c.id)                                                                         AS id,
    (array_agg(c.company_name ORDER BY c.created_at DESC, c.id DESC))[1]              AS company_name,
    (array_agg(c.person_name_en
               ORDER BY (c.person_name_en IS NULL), c.created_at ASC, c.id ASC))[1] AS person_name_en,
    (array_agg(c.person_name_th
               ORDER BY (c.person_name_th IS NULL), c.created_at ASC, c.id ASC))[1] AS person_name_th,
    min(c.created_at)                                                                 AS created_at,
    max(c.updated_at)                                                                 AS updated_at
  FROM lakeshore.company_contact c
  GROUP BY c.person_key;


  -- ─────────────────────────────────────────────────────────────
  -- comparison: one compare run (the header). selected_companies is what the run
  -- matched against; expected_batches is the durable denominator for progress.
  -- ─────────────────────────────────────────────────────────────
  CREATE TABLE lakeshore.comparison (
    id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name               varchar(255),
    -- The companies the run was pointed at. A run scores every friend against the union of
    -- their contacts and keeps the closest single match, so several companies is one run and
    -- one finding — not a merge of several.
    --
    -- NULL/empty is a real kind of run, not a missing value: an import scores its rows against
    -- everything on the other side rather than against a company anybody picked. Which company
    -- each row actually matched is on the row (comparison_result.company_name), because once a
    -- run can name three that is a fact about the match and not about the run.
    selected_companies text[],
    -- WHICH FRIENDS were in the run, by where they came from: 'facebook' | 'linkedin' |
    -- 'business card' | anything a user added to upload_source. Matched against friend.source,
    -- case-insensitively, and stored folded.
    --
    -- NULL/empty is a real kind of run and means EVERY source — exactly as it does for
    -- selected_companies above. It is not "unknown" and it is not "none": a run with no friends in
    -- it is not a run, so the contract boundary normalises an empty array to NULL and readers must
    -- never coalesce this to '{}'.
    --
    -- An array and not the varchar(100) that stood here until 2026-08-03d, because "Facebook and
    -- LinkedIn but not business cards" is one question and belongs in one run. The scalar was never
    -- written by anything — see the migration for why that made the swap a rename.
    --
    -- No FK into upload_source, for the same reason friend.source has none: that table constrains
    -- the picker, not the column, and a run naming a source somebody later deleted is still a run
    -- worth reading.
    sources            text[],
    status             text NOT NULL DEFAULT 'processing'
                        CHECK (status IN ('pending','processing','completed','failed')),
    -- HOW this run compared the names — two axes in one value, '<language>_<type>':
    -- en|th × full|name|surname. The vocabulary lives in extensions/contract/src/compare-by.ts
    -- and is validated there. There is no "both languages" value: 'either' was the default until
    -- 2026-07-27 and scored against both name columns, keeping the better; it is gone, so every
    -- run compares exactly one language and reports the other's names as "Not compared".
    --
    -- NULL resolves to the default ('en_full') rather than to "unknown". Every run the app writes
    -- carries an explicit value, so a null only arises from a row written around the app (the
    -- Database console) or from one predating the column; readers coalesce rather than branch.
    --
    -- No CHECK, and for a different reason than friend.status has none. That column is
    -- written by an external system and an unexpected value must be storable. This one is
    -- only ever written by us — it has no CHECK because adding a value to the vocabulary
    -- later would otherwise mean dropping and rebuilding a constraint by hand, out of band,
    -- against a schema this app is forbidden from issuing DDL against. Enforced at the
    -- contract boundary instead, where a bad value is a 400 rather than a 500.
    compare_by         text,
    -- WHICH ROWS the run covered — the axis, and the one value it takes.
    --
    --   filter_by    'upload' | 'company' | 'owner' | 'file'
    --   filter_value the upload id, the company name, the relationship owner, or the upload id
    --                of the import being re-run
    --
    -- The three columns above narrow a population that something else decided; this one names the
    -- population. While an import was the only way to start a run that distinction did not exist —
    -- the rows were "whatever this file brought" and nothing had to say so. Once the Network page
    -- can re-compare one company, one relationship owner or one past import over data already on
    -- file, a run needs to record which of those it was, or two runs over completely different row
    -- sets store and read back identically.
    --
    -- A PAIR, always written together and always read together. Half a scope is a run nobody can
    -- describe: an axis with no value selects everything while calling itself narrowed. Enforced at
    -- the contract boundary (extensions/contract/src/run-scope.ts), which is also where the
    -- vocabulary lives — these two travel to the external matcher as CSV columns and headers, and
    -- the workflow SELECTS on them (docs/EXTERNAL-MATCHER.md §1c), so the value stored here and the
    -- value branched on there have to be one string spelled once.
    --
    -- No CHECK, for exactly the reason `compare_by` has none: it is only ever written by us, and a
    -- constraint would make adding a fourth scope a hand-applied DDL change against a schema this
    -- app may not issue DDL against. A bad value is a 400 at the route, not a 500 at the INSERT.
    --
    -- NULL is meaningful and is not backfilled: a run predating these columns (added 2026-08-05,
    -- see docs/add-comparison-scope.sql) recorded no scope, and stamping 'upload' on the ones an
    -- import points at would be mostly right and silently wrong for the rest. Readers render no
    -- chip rather than a chip claiming a scope nobody chose.
    filter_by          text,
    filter_value       text,
    expected_batches   integer,                               -- total declared by the matcher (0/NULL = unknown)
    -- Who STARTED this run. Defaulted from the signed-in account (name, else email) at every
    -- creation site; free text, like `upload.uploaded_by`, because it is a label for a human to
    -- read and not a foreign key — an account can be deleted and the run it started is still a run
    -- worth attributing.
    --
    -- Nullable, and the null is meaningful: a run written around the app (the Database console) or
    -- predating this column has no actor on file. The Audit trail then falls back to the uploader
    -- of the import that opened the run, and shows nothing if there is no such import — it never
    -- guesses. NOT the same person as `upload.uploaded_by` in general, for the same reason
    -- `uploaded_by` and `relationship_owner` are different columns: whoever imported a friends list
    -- need not be whoever later pressed Compare against it.
    --
    -- (Mirrored by docs/add-comparison-created-by.sql for live databases.)
    created_by         varchar(255),
    created_at         timestamptz NOT NULL DEFAULT now(),
    updated_at         timestamptz NOT NULL DEFAULT now()
  );
  CREATE INDEX idx_comparison_created ON lakeshore.comparison (created_at DESC);
  -- "Every run scoped to this company / this owner / this file" — what the duplicate check asks.
  -- Partial, so it costs nothing on the legacy rows that carry no scope at all.
  CREATE INDEX idx_comparison_scope ON lakeshore.comparison (filter_by, filter_value)
    WHERE filter_by IS NOT NULL;

  -- comparison_result: the matches, appended one batch at a time.
  CREATE TABLE lakeshore.comparison_result (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comparison_id  bigint NOT NULL REFERENCES lakeshore.comparison(id) ON DELETE CASCADE,
    -- A result row does TWO jobs, and doing both with one representation is what produced the
    -- cross-language double-count. They are separated here:
    --
    --   EVIDENCE — what was compared, as it read at the time → TEXT, both spellings, both sides.
    --              Frozen: a later rename must not rewrite what a past run said.
    --   IDENTITY — which rows this is about                  → ID, nullable FK.
    --              Exact: names collide, and one person has two of them.
    --
    -- The friend's English and Thai names as they stood, written whichever language ran — the
    -- same thing the matcher already does for the contact side. Two columns and not one, because
    -- a Thai run writes `สมชาย ใจดี` and an English run writes `somchai jaidee` for one person,
    -- and counting distinct name strings then reports two friends: `friends − matched = noMatch`
    -- breaks silently, in the flattering direction.
    --
    -- A single `friend_name` stood beside these until 2026-08-03c-drop-comparison-result-friend-name.sql
    -- holding the one spelling a run actually SCORED. It is gone, and with it the ability to say
    -- which of the two was compared from the row alone — `comparison.compare_by` answers that now,
    -- exactly for every run that recorded a language and not at all for the rows where it is NULL.
    -- Its other job was identity: it was the only name an external workflow sent, so it was what
    -- `friend-identity.ts` matched friends on. 2026-08-03b routed every one of those values into
    -- the column its script indicates before the drop, which is what makes the disjunction there
    -- safe to have narrowed.
    --
    -- Both nullable: an external workflow need not send either, and a row that sends neither
    -- resolves to no friend and contributes to no count.
    friend_name_en varchar(255),
    friend_name_th varchar(255),
    person_name_en varchar(255),
    person_name_th varchar(255),
    -- IDENTITY — FOR COUNTING ONLY. Never render a name by following one of these: the text
    -- columns above are the frozen record, and these point at rows that may since have been
    -- renamed. Resolving a display name through an id is exactly how a rename would begin
    -- rewriting history, which the text columns exist to prevent.
    --
    -- ON DELETE SET NULL, never CASCADE. Rolling an import back deletes its `friend` rows
    -- (upload_id … ON DELETE CASCADE), so a cascade here would delete run history as a side
    -- effect of undoing an import. SET NULL leaves the result row intact and degrades it to its
    -- text — the evidence of what was compared outliving the rows it was compared from.
    friend_id          bigint REFERENCES lakeshore.friend(id) ON DELETE SET NULL,
    company_contact_id bigint REFERENCES lakeshore.company_contact(id) ON DELETE SET NULL,
    batch_number   integer,
    -- This row's verdict, same vocabulary as friend.status — and now the whole of the answer.
    --
    -- There was a `matching_score real` beside this, and the split between them was a split of
    -- authority: the matcher owned whether a row was DECIDED, we owned what counted as a match,
    -- re-deriving each row's verdict from its score against MATCH_THRESHOLD on every read. The
    -- score is dropped (see docs/migrations/2026-07-20-drop-matching-score.sql) and the split with
    -- it. The matcher decides both, and the decision is now stored rather than recomputed.
    --
    -- No CHECK, for the same reason friend.status has none: an external system writes this and an
    -- unexpected value must be storable rather than fatal. Every reader goes through rowVerdict.
    --
    -- Defaults to 'pending' rather than 'processing' so a workflow inserting a placeholder row
    -- ahead of its verdict reads as unfinished; both spellings mean unfinished (see
    -- ROW_UNFINISHED_VALUES). Rows the app writes always carry an explicit status, so the default
    -- only ever applies to writers we do not control.
    status         text NOT NULL DEFAULT 'pending',
    -- How close the match was — pg_trgm similarity in [0, 1], for SORTING and DISPLAY only.
    --
    -- This is NOT the `matching_score` that was dropped in 2026-07-20 (see that migration and
    -- add-similarity.sql). That column was authoritative: every read re-derived `status` from it
    -- against a threshold, so it re-graded history when the bar moved. `similarity` is advisory —
    -- it ranks rows and shows how good a match was, and NOTHING reads it to decide match vs no-match.
    -- `status` is still the whole verdict; this only orders and describes it.
    --
    -- Nullable: the internal matcher fills it (it computes this number to decide the row anyway), an
    -- external matcher need not, and rows predating the column have none. Readers sort NULLs last and
    -- show them as "—".
    similarity     real,
    upload_name    varchar(255),                              -- connected uploader, when matcher provides it
    -- Where the matched contact works, as the matcher found them. A run can name several
    -- companies, so this is the row's own answer rather than something derivable from the run.
    -- Nullable: an external workflow need not send it, and rows predating the column have none —
    -- readers then fall back to looking the contact up by name.
    company_name   varchar(255),
    extra          jsonb,                                     -- non-standard matcher fields
    created_at     timestamptz NOT NULL DEFAULT now()
  );
  CREATE INDEX idx_comparison_result_comparison ON lakeshore.comparison_result (comparison_id);
  -- Serves both the distinct-batch progress count and batch-level idempotency.
  CREATE INDEX idx_comparison_result_batch ON lakeshore.comparison_result (comparison_id, batch_number);
  -- The progress poll's verdict tally, and the run table's status filter.
  CREATE INDEX idx_comparison_result_status ON lakeshore.comparison_result (comparison_id, status);
  -- Best-first: `where comparison_id = :id order by similarity desc nulls last`. DESC NULLS LAST
  -- mirrors the query so the ordering is read off the index rather than sorted in memory.
  CREATE INDEX idx_comparison_result_similarity
    ON lakeshore.comparison_result (comparison_id, similarity DESC NULLS LAST);
  -- The Network workspace reads results ACROSS runs (not scoped to one comparison_id), on the
  -- denormalized name/company columns — which the indexes above don't cover. Overview groups by
  -- company; Search looks a contact up by name and by company, per result row. Without these three,
  -- a full-page Search fans out to one sequential scan of this whole table per row on the page
  -- (~2s at 80k contacts / 180k results); with them it is a few ms. See models/network.model.ts.
  CREATE INDEX idx_comparison_result_company_lower ON lakeshore.comparison_result (lower(company_name));
  CREATE INDEX idx_comparison_result_person_en ON lakeshore.comparison_result (person_name_en);
  CREATE INDEX idx_comparison_result_person_th ON lakeshore.comparison_result (person_name_th);
  -- Scopes the Overview to one uploader (their matched-friend and per-company counts).
  CREATE INDEX idx_comparison_result_upload_lower ON lakeshore.comparison_result (lower(upload_name));
  -- Counting distinct FRIENDS rather than distinct name strings — the fix for the bilingual
  -- double-count. `count(distinct coalesce(cr.friend_id, f.id))` uses the first two; the third
  -- serves the join-back that supplies `f.id` for rows with no `friend_id` (an external
  -- workflow, or a row predating the column).
  CREATE INDEX idx_comparison_result_friend ON lakeshore.comparison_result (friend_id);
  CREATE INDEX idx_comparison_result_contact ON lakeshore.comparison_result (company_contact_id);
  CREATE INDEX idx_comparison_result_friend_names
    ON lakeshore.comparison_result (friend_name_en, friend_name_th);

  -- upload.comparison_id → comparison. Declared here rather than on the column, because
  -- `upload` is created before `comparison` is.
  ALTER TABLE lakeshore.upload
    ADD CONSTRAINT upload_comparison_id_fkey
    FOREIGN KEY (comparison_id) REFERENCES lakeshore.comparison(id) ON DELETE SET NULL;


  -- ─────────────────────────────────────────────────────────────
  -- history_sessions: REMOVED. "Past runs" lists the runs themselves (GET /api/comparisons).
  -- comparison_result stores names and scores as text with no FK back to friend /
  -- company_contact, so a finished run is already immutable — there was nothing a saved
  -- snapshot could protect against, only a second copy of the same data in a second shape.
  -- (The DROP above is what removes it from a database that already has it.)
  -- ─────────────────────────────────────────────────────────────


  -- ─────────────────────────────────────────────────────────────
  -- saved_query: a named, re-runnable query from the Database console.
  --   kind='sql'      sql_text holds a read-only SELECT typed into the SQL editor
  --   kind='builder'  spec holds the visual builder's {table, filters, sort} as JSON
  -- created_by is the app_user id of whoever saved it.
  -- (Mirrored by migrations/0014_create_saved_query.ts — keep the two in step.)
  -- ─────────────────────────────────────────────────────────────
  CREATE TABLE lakeshore.saved_query (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       varchar(255) NOT NULL,
    kind       text NOT NULL CHECK (kind IN ('sql','builder')),
    sql_text   text,
    spec       jsonb,
    created_by varchar(255),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
  );
  CREATE INDEX idx_saved_query_created ON lakeshore.saved_query (created_at DESC);


  -- ─────────────────────────────────────────────────────────────
  -- app_user / auth_session: authentication.
  --
  -- Network Intel used to sit behind a website that logged the user in and handed over a JWT —
  -- it only ever *verified* one. It now owns the whole flow, which is what these two tables
  -- are for. password_hash is a self-describing scrypt string (api/src/lib/password.ts);
  -- token_hash is the SHA-256 of the session token the browser holds, so a dump of
  -- auth_session yields nothing that can be replayed as a login.
  --
  -- A session is a ROW, which is the point: it can be revoked. A JWT cannot be.
  -- (Mirrored by migrations/0015_create_auth_tables.ts — keep the two in step.)
  -- ─────────────────────────────────────────────────────────────
  CREATE TABLE lakeshore.app_user (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         varchar(320) NOT NULL,        -- 64 local + @ + 255 domain
    password_hash text NOT NULL,
    name          varchar(255),
    roles         text[] NOT NULL DEFAULT '{}',
    is_active     boolean NOT NULL DEFAULT true,
    last_login_at timestamptz,
    -- Where that last sign-in came from. Overwritten each login, so it is the account's
    -- current whereabouts; the per-session history is auth_session.ip, which dies with the
    -- session. Only meaningful if the API can see the client — behind a proxy that needs
    -- TRUST_PROXY, or this records the proxy. (Added later: docs/add-last-login-ip.sql.)
    last_login_ip varchar(64),
    created_at    timestamptz NOT NULL DEFAULT now(),
    updated_at    timestamptz NOT NULL DEFAULT now()
  );
  -- On lower(email), not email: otherwise Ann@x.com and ann@x.com are two accounts, and
  -- which one you get at login depends on how you typed it.
  CREATE UNIQUE INDEX idx_app_user_email ON lakeshore.app_user (lower(email));

  CREATE TABLE lakeshore.auth_session (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Deleting a user must take their live sessions with them, or they stay signed in.
    user_id      bigint NOT NULL REFERENCES lakeshore.app_user (id) ON DELETE CASCADE,
    token_hash   varchar(64) NOT NULL UNIQUE,   -- sha256 hex of the token the browser holds
    expires_at   timestamptz NOT NULL,
    last_seen_at timestamptz NOT NULL DEFAULT now(),
    user_agent   text,
    ip           varchar(64),
    created_at   timestamptz NOT NULL DEFAULT now()
  );
  CREATE INDEX idx_auth_session_user    ON lakeshore.auth_session (user_id);     -- "sign out everywhere"
  CREATE INDEX idx_auth_session_expires ON lakeshore.auth_session (expires_at);  -- sweep of expired rows

  -- email_otp: the one-time codes emailed during the password + email-code sign-in
  -- (api/src/services/otp-auth.service.ts). code_hash is a scrypt hash of the digits, never
  -- the digits — a 6-digit code is trivially reversible from a fast hash, so it is protected
  -- like a password. Single-use (consumed_at) and short-lived (expires_at); `attempts` caps
  -- wrong guesses. (Mirrored by docs/add-otp-login.sql for live databases.)
  CREATE TABLE lakeshore.email_otp (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     bigint NOT NULL REFERENCES lakeshore.app_user (id) ON DELETE CASCADE,
    purpose     varchar(32) NOT NULL DEFAULT 'login',
    code_hash   text NOT NULL,
    expires_at  timestamptz NOT NULL,
    consumed_at timestamptz,
    attempts    integer NOT NULL DEFAULT 0,
    ip          varchar(64),
    user_agent  text,
    created_at  timestamptz NOT NULL DEFAULT now()
  );
  CREATE INDEX idx_email_otp_user    ON lakeshore.email_otp (user_id);
  CREATE INDEX idx_email_otp_expires ON lakeshore.email_otp (expires_at);


  -- ============================================================================
  -- Optional: keep updated_at fresh (Postgres has no built-in "on update").
  -- Uses EXECUTE PROCEDURE (not EXECUTE FUNCTION) so it works on Postgres 10;
  -- PROCEDURE is still accepted on every newer version too.
  -- ============================================================================
  CREATE OR REPLACE FUNCTION lakeshore.set_updated_at() RETURNS trigger AS $$
  BEGIN
    NEW.updated_at = now();
    RETURN NEW;
  END;
  $$ LANGUAGE plpgsql;

  DROP TRIGGER IF EXISTS trg_upload_updated          ON lakeshore.upload;
  CREATE TRIGGER trg_upload_updated          BEFORE UPDATE ON lakeshore.upload
    FOR EACH ROW EXECUTE PROCEDURE lakeshore.set_updated_at();
  DROP TRIGGER IF EXISTS trg_friend_updated          ON lakeshore.friend;
  CREATE TRIGGER trg_friend_updated          BEFORE UPDATE ON lakeshore.friend
    FOR EACH ROW EXECUTE PROCEDURE lakeshore.set_updated_at();
  DROP TRIGGER IF EXISTS trg_company_contact_updated ON lakeshore.company_contact;
  CREATE TRIGGER trg_company_contact_updated BEFORE UPDATE ON lakeshore.company_contact
    FOR EACH ROW EXECUTE PROCEDURE lakeshore.set_updated_at();
  DROP TRIGGER IF EXISTS trg_comparison_updated      ON lakeshore.comparison;
  CREATE TRIGGER trg_comparison_updated      BEFORE UPDATE ON lakeshore.comparison
    FOR EACH ROW EXECUTE PROCEDURE lakeshore.set_updated_at();
  DROP TRIGGER IF EXISTS trg_saved_query_updated     ON lakeshore.saved_query;
  CREATE TRIGGER trg_saved_query_updated     BEFORE UPDATE ON lakeshore.saved_query
    FOR EACH ROW EXECUTE PROCEDURE lakeshore.set_updated_at();
  DROP TRIGGER IF EXISTS trg_app_user_updated        ON lakeshore.app_user;
  CREATE TRIGGER trg_app_user_updated        BEFORE UPDATE ON lakeshore.app_user
    FOR EACH ROW EXECUTE PROCEDURE lakeshore.set_updated_at();


  -- ============================================================================
  -- Reference queries (how the app uses the shape)
  -- ============================================================================

  -- Rollback an import: just delete its rows (upload_id FK). No orphan check needed.
  --   DELETE FROM lakeshore.friend          WHERE upload_id = :uploadId;   -- (or company_contact)
  --   UPDATE lakeshore.upload SET status = 'rolled_back' WHERE id = :uploadId;

  -- Compare-run progress (numerator computed, never stored → can't drift):
  --   SELECT count(DISTINCT batch_number) AS received_batches
  --     FROM lakeshore.comparison_result WHERE comparison_id = :cmpId;
  --   -- complete when received_batches >= comparison.expected_batches (and > 0)

  -- Row-level progress — the poll that decides an IMPORT is done. An import is finished when the
  -- workflow has stamped every row it was given; a failed row counts as stamped, because the
  -- workflow is never coming back to it. See api/src/models/row-status.ts.
  --   SELECT count(*) FROM lakeshore.friend
  --    WHERE upload_id = :uploadId AND lower(btrim(status)) IN ('pending','processing');
  --   -- finished when this is 0
